export const AuthenticationConstants = {
    LOGIN_REQUEST: 'USER_LOGIN_REQUEST',
    LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    LOGIN_FAILURE: 'USER_LOGIN_FAILURE',
    LOGOUT: 'USER_LOGOUT',
}

export const UserConstants = {
    INFO_ACCOUNT_REQUEST: 'USER_INFO_ACCOUNT_REQUEST',
    INFO_ACCOUNT_SUCCESS: 'USER_INFO_ACCOUNT_SUCCESS',
    INFO_ACCOUNT_FAILURE: 'USER_INFO_ACCOUNT_FAILURE',
}