export const FavoriteConstants = {
    FAVORITE_LIST_REQUEST: 'GET_LIST_FAVORITE',
    FAVORITE_LIST_SUCCESS: 'GET_LIST_FAVORITE_SUCCESS',
    FAVORITE_LIST_FAILURE: 'GET_LIST_FAVORITE_FAILURE',

    FAVORITE_REQUEST: 'MOVIE_FAVORITE_REQUEST',
    FAVORITE_SUCCESS: 'MOVIE_FAVORITE_SUCCESS',
    FAVORITE_FAILURE: 'MOVIE_FAVORITE_FAILURE',
}

export const VotedConstants = {
    VOTED_LIST_REQUEST: 'GET_LIST_VOTED',
    VOTED_LIST_SUCCESS: 'GET_LIST_VOTED_SUCCESS',
    VOTED_LIST_FAILURE: 'GET_LIST_VOTED_FAILURE',

    VOTED_REQUEST: 'ADD_VOTED_REQUEST',
    VOTED_SUCCESS: 'ADD_VOTED_SUCCESS',
    VOTED_FAILURE: 'ADD_VOTED_FAILURE',
}

