# Generated by Django 2.2.6 on 2019-11-06 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('count', models.IntegerField(default=0)),
                ('type', models.CharField(choices=[('ricerca_suggerita', 'Ricerca singola'), ('ricerca_completa', 'Ricerca completa')], max_length=50)),
            ],
        ),
    ]
