# Generated by Django 2.2.6 on 2019-11-06 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id_person', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('second_name', models.CharField(max_length=30)),
                ('birth_date', models.DateField(blank=True)),
                ('type', models.CharField(choices=[('actor', 'Actor'), ('director', 'Director'), ('writer', 'Writer')], max_length=20)),
            ],
            options={
                'ordering': ['second_name', 'first_name'],
            },
        ),
    ]
