# Generated by Django 2.2.6 on 2019-11-11 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id_person', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('second_name', models.CharField(max_length=30)),
                ('type', models.CharField(choices=[('actor', 'Actor'), ('director', 'Director'), ('writer', 'Writer')], max_length=20)),
                ('gender', models.CharField(choices=[('man', 'Man'), ('woman', 'Woman')], max_length=10)),
                ('birth_date', models.DateField(null=True)),
                ('death_date', models.DateField(null=True)),
                ('nationality', models.CharField(max_length=10, null=True)),
                ('place_of_birth', models.CharField(max_length=200, null=True)),
                ('imdb_id', models.CharField(max_length=200, null=True)),
                ('biography', models.TextField(null=True)),
            ],
            options={
                'ordering': ['second_name', 'first_name'],
            },
        ),
    ]
