# Generated by Django 2.2.6 on 2019-11-06 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_auto_20191106_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='death_date',
            field=models.DateField(null=True),
        ),
    ]
