# Generated by Django 2.2.6 on 2019-11-06 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0003_auto_20191106_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('man', 'Man'), ('woman', 'Woman')], default='Man', max_length=10),
            preserve_default=False,
        ),
    ]
