# Generated by Django 2.2.6 on 2019-11-06 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0004_person_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='birth_date',
            field=models.DateField(null=True),
        ),
    ]
