# Generated by Django 2.2.6 on 2019-11-11 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_character', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id_film', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=80)),
                ('original_title', models.CharField(max_length=80, null=True)),
                ('imdb_id', models.CharField(max_length=10, null=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('release_date', models.DateField(null=True)),
                ('vote_average', models.FloatField(default=0.0)),
                ('vote_counter', models.IntegerField(default=0)),
                ('directors', models.ManyToManyField(related_name='Directors', to='person.Person')),
                ('genres', models.ManyToManyField(related_name='Genres', to='film.Genre')),
                ('keywords', models.ManyToManyField(related_name='Keywords', to='film.Keyword')),
                ('people', models.ManyToManyField(related_name='Cast', through='film.Cast', to='person.Person')),
                ('writers', models.ManyToManyField(related_name='Writers', to='person.Person')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='cast',
            name='film',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='film.Film'),
        ),
        migrations.AddField(
            model_name='cast',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.Person'),
        ),
    ]
