# Generated by Django 2.2.6 on 2019-11-06 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id_film', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=80)),
                ('original_title', models.CharField(max_length=80)),
                ('vote_average', models.FloatField(default=0.0)),
                ('vote_counter', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('imdb_id', models.CharField(max_length=10, unique=True)),
                ('release_date', models.DateField(blank=True)),
                ('cast', models.ManyToManyField(related_name='Cast', to='person.Person')),
                ('directors', models.ManyToManyField(related_name='Directors', to='person.Person')),
                ('genres', models.ManyToManyField(related_name='Genres', to='film.Genre')),
                ('keywords', models.ManyToManyField(related_name='Keywords', to='film.Keyword')),
                ('writers', models.ManyToManyField(related_name='Writers', to='person.Person')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
